module.exports =  {
    ADMIN_CREATE_VIRTUAL_ACCOUNT:"ADMIN_CREATE_VIRTUAL_ACCOUNT",
    RETRIEVE_SINGLE_VIRTUAL_ACCOUNT:"RETRIEVE_SINGLE_VIRTUAL_ACCOUNT",
    BANK_LIST:"BANK_LIST",
    NAME_ENQUIRY:"NAME_ENQUIRY",
    SINGLE_FUND_TRANSFER:"SINGLE_FUND_TRANSFER",
    VIRTUAL_ACCOUNT_FUND_TRANSFER:"VIRTUAL_ACCOUNT_FUND_TRANSFER",
    TRANSACTION_STATUS_QUERY:"TRANSACTION_STATUS_QUERY",
    RETRIEVE_VIRTUAL_ACCOUNT_BALANCE:"RETRIEVE_VIRTUAL_ACCOUNT_BALANCE",
    ADMIN_MAIN_ACCOUNT_TRANSACTIONS:"ADMIN_MAIN_ACCOUNT_TRANSACTIONS",
    ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS:"ADMIN_MAIN_ACCOUNT_FILTERED_TRANSACTIONS",
    ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS:"ADMIN_VIRTUAL_ACCOUNT_TRANSACTIONS",
    ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS:"ADMIN_VIRTUAL_ACCOUNT_FILTERED_TRANSACTIONS",
    FUND_VIRTUAL_ACCOUNT:"FUND_VIRTUAL_ACCOUNT",
    WITHDRAW_VIRTUAL_ACCOUNT:"WITHDRAW_VIRTUAL_ACCOUNT"
}